#pragma once

#include "Scenes/Data/NavMeshSimulationSceneBenchmarkResult.h"
#include "Scenes/Data/NavMeshSimulationSceneBenchmarkStats.h"

class NavMeshSimulationSceneBenchmarks
{
public:
	NavMeshSimulationSceneBenchmarkStats UpperSurfaceStats;
	NavMeshSimulationSceneBenchmarkStats UpperSurfaceSubDivisionStats;
	NavMeshSimulationSceneBenchmarkStats UpperSurfaceBarycentricSubDivisionStats;

	NavMeshSimulationSceneBenchmarkResult UpperSurfaceBenchmark;
	NavMeshSimulationSceneBenchmarkResult UpperSurfaceSubDivisionBenchmark;
	NavMeshSimulationSceneBenchmarkResult UpperSurfaceBarycentricSubDivisionBenchmark;
private:
};
