#include "NavMeshSimulationSceneBenchmarks.h"

NavMeshSimulationSceneBenchmarks::NavMeshSimulationSceneBenchmarks()
{
	UpperSurfaceBenchmarkHandle = UpperSurfaceBenchmark.CreateHandle();
	UpperSurfaceSubDivisionBenchmarkHandle = UpperSurfaceSubDivisionBenchmark.CreateHandle();
	UpperSurfaceBarycentricSubDivisionBenchmarkHandle = UpperSurfaceBarycentricSubDivisionBenchmark.CreateHandle();

	UpperSurfaceDijkstraBenchmarkHandle = UpperSurfaceDijkstraBenchmark.CreateHandle();
	UpperSurfaceSubDivisionDijkstraBenchmarkHandle = UpperSurfaceSubDivisionDijkstraBenchmark.CreateHandle();
	UpperSurfaceBarycentricSubDivisionDijkstraBenchmarkHandle = UpperSurfaceBarycentricSubDivisionDijkstraBenchmark.CreateHandle();
}

void NavMeshSimulationSceneBenchmarks::Update()
{
	UpperSurfaceBenchmark.Update(UpperSurfaceBenchmarkHandle);
	UpperSurfaceSubDivisionBenchmark.Update(UpperSurfaceSubDivisionBenchmarkHandle);
	UpperSurfaceBarycentricSubDivisionBenchmark.Update(UpperSurfaceBarycentricSubDivisionBenchmarkHandle);

	UpperSurfaceDijkstraBenchmark.Update(UpperSurfaceDijkstraBenchmarkHandle);
	UpperSurfaceSubDivisionDijkstraBenchmark.Update(UpperSurfaceSubDivisionDijkstraBenchmarkHandle);
	UpperSurfaceBarycentricSubDivisionDijkstraBenchmark.Update(UpperSurfaceBarycentricSubDivisionDijkstraBenchmarkHandle);
}
